### ISSUE TITLE
better debug output using graphviz

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/polonius#12]
Right now we always communicate in "raw dumps" of tuples. This is kind of a pain in the neck. It'd be nice to create a [graphviz](https://www.graphviz.org/) file that contains both the *input tuples* and the *output tuples* for each point. We have in the `AllFacts` data the edges between CFG nodes, so we can arrange things this way fairly easily. Eventually we could grow with more information if we had it, but for now if we dump the tuples in graph form, it should be possible to then correlate with the MIR dumps.

**Comment by nikomatsakis** [comment]
I imagine it looking something like this template:

https://graphviz.gitlab.io/_pages/Gallery/directed/datastruct.html

There would be a header with the label (e.g., `Start(bb3[2])`), and then one row per relevant fact at that location (input facts first, output facts second, maybe with a distinct background per kind of fact). Then edges would leave the "last" fact and enter at the header.

**Comment by nikomatsakis** [comment]
Note the graphviz source is available for that sample, too:

https://graphviz.gitlab.io/_pages/Gallery/directed/datastruct.gv.txt

**Comment by porglezomp** [comment]
I'd like to take this issue.

**Comment by nikomatsakis** [comment]
@porglezomp cool! let me know how it goes. @qmx had also mentioned doing stuff, but I don't know if they started anything (since no comment, gonna assume no)

**Comment by porglezomp** [comment]
Is there any particular command line interface envisioned for these yet? Should these just show up as `.dot` files in the output directory? Should it be explicitly enabled or disabled?

**Comment by nikomatsakis** [comment]
@porglezomp I did not have a specific idea; I guess I would add a flag like `--dot <dir>` and then write the files into the directories with names based on the names of the inputs?

**Comment by vakaras** [comment]
Any progress on this? Can we steal this issue?

**Comment by nagisa** [comment]
Go ahead.

**Comment by yati-sagade** [comment]
I'll pick this up.

**Comment by utaal** [comment]
WIP branch: https://github.com/utaal/polonius/tree/graphviz-output
