### ISSUE TITLE
allow command line arguments to be given to differential dataflow

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/polonius#25]
Right now, when we invoke differential-dataflow, we give in no command line arguments:

https://github.com/rust-lang-nursery/borrow-check/blob/4945c130cb1f3af7c072dc9856b6fe21b3a9f1f7/src/output/timely_opt.rs#L51

As you can see in [the docs.rs page](https://docs.rs/timely/0.5.1/timely/execute/fn.execute_from_args.html), though, there are a number of arguments for things like using multiple threads. I actually think it's better if we avoid threads by default, but it'd be interesting to see what effects those flags have. We should extend our CLI to permit us to pass in "timely dataflow" flags, and then thread them through to that line above.

We can also pass them to the naive algorithm, here:

https://github.com/rust-lang-nursery/borrow-check/blob/4945c130cb1f3af7c072dc9856b6fe21b3a9f1f7/src/output/naive.rs#L34

**Comment by nikomatsakis** [comment]
Maybe we should just extend our CLI with the `-w` switch to indicate how many worker threads to use.  I don't think we want to mess with multiple processes.

**Comment by lqd** [comment]
Note: most of #30 was removed in the switch-to-datafrog PR, and maybe we can close this issue ?
