### ISSUE TITLE
location-insensitive first pass

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/polonius#29]
Building on my notes from #4 (cc @spastorino @bobtwinkles), as well as the promising results from https://github.com/rust-lang/rust/pull/50593, I was thinking that one way to get things faster would be to begin with a "coarser-grained" analysis and then -- only for those loans that resulted in an error -- do the full analysis.

This will build on #4 -- we need the set of `Invalidated` facts to make this work, but it's a separate body of work. That is, we can implement this 'location-insensitive' analysis as an experimental pre-pass and start to measure it etc.

Roughly speaking, the idea would be to first create a "location-insensitive" subset relation. Unlike the current rules, we would never "remove" things from this relation. The rules would be very simple, I think actually just this:

```
subset(R1, R2) :- outlives(R1, R2, _P).
```

Then we would propagate loans along this subset relation, again ignoring location:

```
requires(R1, L1) :- borrow_region(R1, L1, _P).
requires(R2, L1) :- requires(R1, L1), subset(R1, R2).
```

In fact, even these very simple rules are a kind of transitive closure, and hence we might find that we want to speed them up. But let's assume it's fast enough for now.

Now we can figure out which loans **might** be invalidated at each point:

```
potential_errors(L, P) :-
  invalidated(L, P),
  requires(R, L),
  region_live_at(R, P).
```

Once we have the set of *potential errors*, we can use those to target the more precise analysis — but now we know that we only care about the loans where we found *potential errors*.

**Comment by nikomatsakis** [comment]
Some more notes [are available on Zulip](https://rust-lang.zulipchat.com/#narrow/stream/122657-wg-nll/topic/location-insensitive.20pre-pass.20(.2329))

**Comment by nikomatsakis** [comment]
Some notes on how we can integrate the location insensitive and sensitive analyses. Presuming that we have found a set `potential_errors(L, P)` of potential errors (this loan `L` is invalidated at the loan `P`, and the location insensitive analysis indicated that it was still live), then we can use that to restrict the info we compute to *just* what is needed to validate this analysis. 

Let's say we just start with a set of loans that may be invalidated while live. We can then compute a set of regions that may be required by those loans using `requires_anywhere`. This set, in turn, we can use to narrow down the base `outlives` facts we give to `subset`:

https://github.com/rust-lang-nursery/polonius/blob/6e9d8b778aba1e8746fa02bb456ae237ce29c25d/src/output/timely_opt.rs#L106

Actually, writing this, I realize it's not entirely obvious what this should look like, and I have to run, so I'm going to stop here without really saying much. :)

**Comment by spastorino** [comment]
Done in #41 and #34 adds potential_errors.
