### ISSUE TITLE
factor out the `TimelyOpt` solver into its own crate

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/polonius#31]
It should have as little of the surrounding code as we can get away with. For example, it will need the `AllFacts`, but can hopefully avoid the interner. This will be useful when we try to link this stuff into rustc.

cc @qmx

**Comment by nikomatsakis** [comment]
Some notes: as a first step for this, we should make a library that *just* contains the `AllFacts` definitions (and maybe the code for serializing them?). Then we can try to make rustc use this library so they share a definition of `AllFacts`.

One complication (minor though): rustc uses its own types (e.g., `RegionVid`) for some of the indices. We ought to be able to convert back and forth I imagine though.

**Comment by lqd** [comment]
Is this issue still relevant for rustc-integration ?

**Comment by qmx** [comment]
@lqd I'm not sure tbh, maybe @nikomatsakis can say more about it

**Comment by nikomatsakis** [comment]
sort of but let's close this and make a fresh one
