### ISSUE TITLE
add `Invalidated` tuples

### ISSUE THREAD

**Issue by nikomatsakis** [rust-lang-nursery/polonius#4]
This requires modifying both rustc and borrow-check. The idea is to add the `Invalidated` tuples described [in my blog post](http://smallcultfollowing.com/babysteps/blog/2018/04/27/an-alias-based-formulation-of-the-borrow-checker/#defining-an-error). We would begin by modifying rustc [as described in this gitter log](https://gitter.im/rust-impl-period/WG-compiler-nll?at=5ae8c9e693dc5e5cdb43cc22):

- Today, after computing the borrows in scope, we walk the MIR and invoke `check_access_for_conflict`:
  - that walks over the loans in scope and compares the accessed path against the borrowed path
- Instead, we would walk the MIR ahead of time, before "borrows in scope" are computed:
  - for each access, we would walk **all** loans and do the same comparison
  - if the access would conflict with the loan, we generate a `invalidated(L, P)` fact

This will require some refactoring of borrow check to extract the relevant code. Eventually, I think this can be made extra efficient as well, but basically indexing the paths borrowed by a loan. But we can begin with simple stuff and worry about that later.

Then we would have to extend the `AllFacts` definitions in rustc and this repo to include `Invalidated` facts.

Once those facts are available, we should open a separate issue to discuss how best to make use of them.

**Comment by nikomatsakis** [comment]
cc @bobtwinkles @KiChjang -- I thought one of you two might be up for this. I think that adding this support to rustc is pretty high priority because it's likely a good "enabler" for further improvements.

**Comment by nikomatsakis** [comment]
also possibly @spastorino

**Comment by spastorino** [comment]
I can tackle this

**Comment by nikomatsakis** [comment]
So @bobtwinkles made good progress the other day in [this rustc branch](https://github.com/bobtwinkles/rust/tree/nll_facts_invalidate). I'm now looking a bit past that point --

It seems like we would want to do a few things here, and we can play around with them now by synthesizing the "Facts" files.

**Step 1.** First, we need to add a `invalidated` field to `AllFacts`:

https://github.com/rust-lang-nursery/borrow-check/blob/4945c130cb1f3af7c072dc9856b6fe21b3a9f1f7/src/facts.rs#L3-L5

Something like

```rust
invalidated: Vec<(Loan, Point)>
```

then we would need to make that compile loading facts from `invalidated.facts`. 

**Step 2.** One very simple (and maybe useless, but I'm not sure) optimization would be to detect those loans that are not invalidated **anywhere at all**. We can just fully ignore those loans in the `requires` calculations. But let's leave a description of how to do that for later.

**Comment by nikomatsakis** [comment]
Had some thoughts about the second part. I was thinking that we could try to compute the  "subset" of the computation that is relevant to a particular loan — then we might do that for each loan in turn. Not sure how useful this would be yet but I imagine it might work like this:

1. First, we would compute the subset relation but **without** reference to location. This ought to be fast. 
2. Next, we would have a set that represents "loans we care about". For each loan in that set, we take its associated region (identified by the `borrow_region` fact associated with tha tloan). If we compute the transitive closure of things reachable from that primary region, this gives us a set of regions that *might potentially* carry the loan (this is also position agnostic).
3. We can then restrict the `subset` (and `requires`) computations to regions in that set.

Finally, we can grow the set of loans we care about over time and that should grow more subset computations etc. (Differential dataflow should make that incremental.)

If nothing else, this might allow us to hide some latency -- not sure how useful that would be.

It might also allow us to compute an **overapproximation** -- basically, ignoring location information except when we really care about it -- but I have to think a bit more about how that works.
